backend:
  name: git-gateway
  branch: main  # ou master selon ton dépôt GitHub

media_folder: "images/uploads" # Dossier où seront stockées les images
public_folder: "/images/uploads"

locale: 'fr'

site_url: https://serviceepgt.netlify.app

collections:
  - name: "articles"
    label: "Articles"
    folder: "contenu/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "temoignages"
    label: "Témoignages"
    folder: "contenu/temoignages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Avis", name: "avis", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "contact"
    label: "Contact"
    files:
      - file: "contenu/contact.md"
        label: "Page Contact"
        name: "contact"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Message", name: "message", widget: "text" }

  - name: "a_propos"
    label: "À propos"
    files:
      - file: "contenu/a_propos.md"
        label: "À propos de moi"
        name: "a_propos"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }



